_wandb:
    value:
        cli_version: 0.24.2
        e:
            gamxnc0kby1ljmr8d5bta0asb3pa2nmt:
                apple:
                    ecpuCores: 6
                    gpuCores: 10
                    memoryGb: 16
                    name: Apple M4
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "1073741824"
                codePath: src/main.py
                codePathLocal: src/main.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "494384795648"
                        used: "215777611776"
                email: emanuele.pasquini@edu.unifi.it
                executable: /Users/emanuelepasquini/.pyenv/versions/CVvenv/bin/python
                git:
                    commit: c8e4b8367d5b32d9d77709af7fa99773b8d0a456
                    remote: https://github.com/Pasqem09-zoo/platonic-representations.git
                host: MacBook-Pro-di-emanuele-2.local
                memory:
                    total: "17179869184"
                os: macOS-26.2-arm64-arm-64bit
                program: /Users/emanuelepasquini/Library/CloudStorage/GoogleDrive-emanuele.pasquini@edu.unifi.it/Il mio Drive/università/MAGISTRALE/computer vision/platonic-representations/src/main.py
                python: CPython 3.12.4
                root: /Users/emanuelepasquini/Library/CloudStorage/GoogleDrive-emanuele.pasquini@edu.unifi.it/Il mio Drive/università/MAGISTRALE/computer vision/platonic-representations
                startedAt: "2026-02-09T17:50:23.436378Z"
                writerId: gamxnc0kby1ljmr8d5bta0asb3pa2nmt
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.4
            "5": 0.24.2
            "12": 0.24.2
            "13": darwin-arm64
architecture:
    value: SimpleCNN
dataset:
    value: CIFAR10
epochs:
    value: 10
seed:
    value: 2
